# Generated by Django 5.2 on 2025-05-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='assigned_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_node', to='Main.patients'),
        ),
        migrations.AlterField(
            model_name='readings',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='Main.patients'),
        ),
        migrations.AlterField(
            model_name='readings',
            name='urine',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dehidrasi Berat'), (1, 'Dehidrasi Sedang'), (2, 'Dehidrasi Ringan'), (3, 'Cukup'), (4, 'Baik')]),
        ),
    ]
