# Generated by Django 5.2 on 2025-05-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_nodes_assigned_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(help_text='nomor telpon indonesia', max_length=100),
        ),
    ]
